### ISSUE TITLE
get edittext value

### ISSUE THREAD

**Issue by ririswijaya** [drozdzynski/Steppers#18]
hello. thank you for your effort for making this stepper. i would like to ask how to retrieve edit text value if i put edittext inside fragment 1?

**Comment by drozdzynski** [comment]
You should create interface:
```
public interface OnChangeText {
    void change();
}
```
inside fragment, and use function setOnChangeTextListener where you want listen to change text.

**Comment by ririswijaya** [comment]
ok sir, thank you for your time.
