### ISSUE TITLE
Change Button Label

### ISSUE THREAD

**Issue by Turbiani** [drozdzynski/Steppers#21]
Hi, whats up ?

How I Change the buttons text ? The default text to PositiveButtons is CONTINUE, i need to change to my country language. How do i do this ?

**Comment by drozdzynski** [comment]
First read about translate app with resource files: [https://developer.android.com/guide/topics/resources/localization.html](https://developer.android.com/guide/topics/resources/localization.html)

Next add in strings file ( for your lang ) this lines:
```
    <string name="step_continue">Continue</string>
    <string name="step_finish">Finish</string>
    <string name="step_cancel">Cancel</string>
```
And translate them to your language

**Comment by Turbiani** [comment]
Thanks a lot Krystian.

Happy Holidays

**Comment by drozdzynski** [comment]
If you like my work, support by [donation](https://supporterhq.com/support/dqfwyaghpju5ijbt3pzyl5uv6/steppers) :-)
