### ISSUE TITLE
Android Studio can't resolve the library.

### ISSUE THREAD

**Issue by kizitonwose** [drozdzynski/Steppers#28]
For some reason, Android Studio can't resolve the library when I add it to my project. I thought it's an issue with my machine so I tried it [here](http://www.methodscount.com/?lib=me.drozdzynski.library.steppers%3Asteppers%3A1.0.0) and the website can't resolve it either. This implies that the library is not available on jCenter or Maven Central or JitPack. 

The README suggests `compile 'me.drozdzynski.library.steppers:steppers:1.0.0'` but this does not work, at least not on my end.

Am I missing something? Is it hosted somewhere else?

**Comment by drozdzynski** [comment]
Sorry, I forgot to make full release of 1.0.0, it should be available in few hours.

**Comment by kizitonwose** [comment]
Alright. I'll try again in a few hours.

**Comment by kizitonwose** [comment]
@drozdzynski It's been over 48 hours, still not working.

**Comment by drozdzynski** [comment]
It's weird, because it's available in [maven](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22me.drozdzynski.library.steppers%22)

**Comment by kizitonwose** [comment]
Oh, just tried again and it worked. Closing this issue now.
