### ISSUE TITLE
Vertical Recycler does not get scrolled inside the layout

### ISSUE THREAD

**Issue by ArunPandiyan** [drozdzynski/Steppers#6]
I passed a custom fragment as one of StepperItem, the fragment contains vertical Recyclerview and horizontal Recyclerview inside it. The horizontal Recyclerview is getting scrolled perfectly. But the Vertical Recyclerview  does not gets scrolled. Though when i used Mouse in as input(for emulator as Genymotion) it gets scrolled but the whole view is getting Scrolled at the same time the Vertical Recyclerview inside the fragment gets scrolled. How do i properly handle this situation?

**Comment by drozdzynski** [comment]
I had same problem with ListView ( Recycler View not checked ) and fix it with this:

```
final ListView listView = (ListView) rootView.findViewById(R.id.listView);

listView.setOnTouchListener(new View.OnTouchListener() {
    @Override
    public boolean onTouch(View v, MotionEvent event) {
        v.getParent().requestDisallowInterceptTouchEvent(true);
        return false;
    }
});
```

**Comment by ArunPandiyan** [comment]
It works in recyclerview. Thanks ;)
