### ISSUE TITLE
Adding third fragment to the list returns null pointer exception.

### ISSUE THREAD

**Issue by ArunPandiyan** [drozdzynski/Steppers#7]
It shows error in SteppersAdapter.java

> ```
>     if(fragmentManager.getFragments() != null) {
>         List<Fragment> fragments = fragmentManager.getFragments();
>         for(Fragment fragment : fragments) {
>             Log.d("Fragments", fragment.toString());
>         }
>     }
> ```

my implementation of adding fragments to Arraylist of SteppersItem as follows.

`SteppersView steppersView = (SteppersView) findViewById(R.id.steppersView);

```
    SteppersView.Config steppersViewConfig = new SteppersView.Config();
    steppersViewConfig.setOnFinishAction(new OnFinishAction() {
        @Override
        public void onFinish() {
            Toast.makeText(AddAppointmentActivity.this, "Appointment Created!", Toast.LENGTH_SHORT).show();

        }
    });

    steppersViewConfig.setOnCancelAction(new OnCancelAction() {
        @Override
        public void onCancel() {
            Toast.makeText(AddAppointmentActivity.this, "Appointment Discarded!", Toast.LENGTH_SHORT).show();
        }
    });

    steppersViewConfig.setFragmentManager(getSupportFragmentManager());
    ArrayList<SteppersItem> steps = new ArrayList<>();

    stepFirst = new SteppersItem();
    stepFirst.setLabel("Choose Patient to get Appointment");
    stepFirst.setSubLabel("Specify the time of Appointment");
    chooseDateFragment = new ChooseDateFragment();
    chooseDateFragment.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            switch(v.getId()){
                case R.id.btnChangeDate: /** Start a new Activity MyCards.java */
                    showDatePicker();
                    break;
            }
        }
    });

    stepFirst.setFragment(chooseDateFragment);
    stepFirst.setPositiveButtonEnable(false); //Todo: change to true after completing


    stepSecond = new SteppersItem();
    stepSecond.setLabel("Choose your Symptoms");
    stepSecond.setSubLabel("Select from the below list");
    ChooseSymptomListFragment p1=new ChooseSymptomListFragment();
    stepSecond.setFragment(p1);
    stepSecond.setPositiveButtonEnable(false);

    stepThird=new SteppersItem();
    stepThird.setLabel("Choose Payment Option");
    stepThird.setSubLabel("");
    ChoosePaymentFragment p2=new ChoosePaymentFragment();

    stepThird.setFragment(p2);
    stepThird.setPositiveButtonEnable(false);
    steps.add(stepFirst);
    steps.add(stepSecond);
    steps.add(stepThird);





    steppersView.setConfig(steppersViewConfig);
    steppersView.setItems(steps);
    steppersView.build();
```

`
I don't understand what is the problem in the code.
First both fragments loads perfectly, on clicking continue on the secondStep application throws NullPointerException. I exchanged the fragments order of loading. Nothing helps.

 Help me Out. Thanks !

**Comment by ArunPandiyan** [comment]
I managed to load the third fragment, but its overlapping over the first fragment
![image](https://cloud.githubusercontent.com/assets/10300987/14452039/4690266c-00a9-11e6-87eb-ecc0d248845d.png)

**Comment by drozdzynski** [comment]
About first issue I must check what's going on 😄  about overlapping fragments, did you use version **0.3.3-SNAPSHOT** ?

**Comment by ArunPandiyan** [comment]
No i used **0.3.2 SNAPSHOT**

**Comment by drozdzynski** [comment]
In **0.3.3-SNAPSHOT** I fix issue with overlapping fragments.

**Comment by ArunPandiyan** [comment]
I tried 0.3.3 SNAPSHOT, now the first fragment goes blank.

**Comment by ArunPandiyan** [comment]
i added the same 1st fragment twice using new variable. It doesn't shows on 1st step but it is visible on 2nd step.

**Comment by ArunPandiyan** [comment]
I dont know what happened, it work again. Did a clean & build with uninstalling previous version in device.
