### ISSUE TITLE
Override continue button? and Previous button?

### ISSUE THREAD

**Issue by derrysd** [drozdzynski/Steppers#9]
Hello,
It's a pretty library, but need some additions.
is there a way to overide continue button?
and make previous button?

**Comment by juhor13** [comment]
Has anyobody found a solution for this? Very interested

**Comment by vayalasp** [comment]
I also interested. I also want to change buttom continue status from fragment...

**Comment by Honest-Objections** [comment]
There's now a pull request for the ability to override continue. Haven't looked at going to previous steps, but added a function that will let you go forward to a step so you can skip multiple related ones at once.

**Comment by drozdzynski** [comment]
I will tomorrow look at this pullreq, merge and close issues if is all good.
